### ISSUE TITLE
error on running test data

### ISSUE THREAD

**Issue by jliu678** [broadinstitute/GeLiNEA#2]
Hi,

Tests passed, but `run -n "testNetwork.txt" -s "testGeneSets.txt" -l  "testGeneList.txt" -o "1.txt" -b 50` show errors as below.

All above input are the files from test/data/

Thanks a lot for providing the GeliNEA that should be expected to be greatly popular soon.
 

```
[info] Run completed in 360 milliseconds.
[info] Total number of tests run: 85
[info] Suites: completed 9, aborted 0
[info] Tests: succeeded 85, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 1 s, completed Nov 25, 2020 5:07:46 PM


sbt:gelinea> run -n "testNetwork.txt" -s "testGeneSets.txt" -l  "testGeneList.txt" -o "1.txt" -b 50

[info] Running org.broadinstitute.cbts.gelinea.GeLiNEA -n testNetwork.txt -s testGeneSets.txt -l testGeneList.txt -o 1.txt -b 50
Nov 25, 2020 5:08:01 PM org.broadinstitute.cbts.gelinea.GeLiNEA$ apply
INFO: network loaded: 10 nodes, 9 edges
Nov 25, 2020 5:08:01 PM org.broadinstitute.cbts.gelinea.GeLiNEA$ apply
INFO: 2 gene sets loaded
Nov 25, 2020 5:08:01 PM org.broadinstitute.cbts.gelinea.GeLiNEA$ apply
INFO: gene list loaded, size = 4
[error] (run-main-4) java.lang.ArrayIndexOutOfBoundsException: 10
[error] java.lang.ArrayIndexOutOfBoundsException: 10
[error]         at org.broadinstitute.cbts.gelinea.graph.DegreeBinMap.$anonfun$nodesByDegreeBin$2(DegreeBinMap.scala:76)
[error]         at org.broadinstitute.cbts.gelinea.graph.DegreeBinMap.$anonfun$nodesByDegreeBin$2$adapted(DegreeBinMap.scala:74)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error]         at org.broadinstitute.cbts.gelinea.graph.Graph.foreach(Graph.scala:26)
[error]         at org.broadinstitute.cbts.gelinea.graph.DegreeBinMap.nodesByDegreeBin(DegreeBinMap.scala:74)
[error]         at org.broadinstitute.cbts.gelinea.GeLiNEA.<init>(GeLiNEA.scala:90)
[error]         at org.broadinstitute.cbts.gelinea.GeLiNEA$.apply(GeLiNEA.scala:59)
[error]         at org.broadinstitute.cbts.gelinea.GeLiNEA$.main(GeLiNEA.scala:32)
[error]         at org.broadinstitute.cbts.gelinea.GeLiNEA.main(GeLiNEA.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 0 s, completed Nov 25, 2020 5:08:01 PM
```

**Comment by vdancik** [comment]
It is not very useful to use bin size 50 for a network of 10 nodes, I would suggest to use `-b 1` or `-b 2` .

**Comment by jliu678** [comment]
thanks a lot, that solves the problem. 

But could you please describe a little about what the bin size is for and how to properly set it? I have not found related comments in your nature paper and its supplement, though I believe your tool is worth much more demonstration.
